### ISSUE TITLE
Repacking  nsp->nsz->nsp

### ISSUE THREAD

**Issue by 64ghost** [nicoboss/nsz#116]
After translating nsp->nsz and back nsz->nsp. The resulting nsp is larger. The reason is that the data starts at address 0x8000. Up to address 0x8000 filled with zeros. Is it possible to reduce the void to a minimum.

**Comment by blawar** [comment]
I am skeptical that the 0x8000 offset is the reason. If that was true, there would be dataloss. It is likely that you are simply using different compression settings.

**Comment by nicoboss** [comment]
@64ghost This is fixed in the latest [NSZ v4.3.0](https://github.com/nicoboss/nsz/releases) release. The padding of the source NSP is now kept during compression/decompression making them always bit-identical (especially if --keep-delta is specified). The option --remove-padding was added to remove the padding of existing NSP/NSZ files to make them nxdumptool/no-intro compliant.
