### ISSUE TITLE
NSZ 4.1.0 portable deleting nsz automatically

### ISSUE THREAD

**Issue by mrdude2478** [nicoboss/nsz#126]
Converted xci to nsp game - when trying to compress the nsp the nsz get created and verified 100%, on completion of verification the created compressed nzx is automatically deleted by the program without any user intervention.

Just to note: the converted xci to nsp game installs and runs properly on the switch prior to compression - so there's no issues with the nsp.

**Comment by nicoboss** [comment]
Thanks a lot for leting me know. This is probably a dublicate of either https://github.com/nicoboss/nsz/issues/123 or https://github.com/nicoboss/nsz/issues/124. This should be fixed on latest master and will be fixed in the next release. Sorry for not having created a new release since I fixed those very major issues. I will for sure do another release somewhere in the next week.

**Comment by nicoboss** [comment]
This issue should be fixed in the latest [NSZ v4.1.0](https://github.com/nicoboss/nsz/releases/tag/4.2.0) release. Please let me know if you still experience this issue on the latest release.
