### ISSUE TITLE
AttributeError w/ args.long on Arch Linux.

### ISSUE THREAD

**Issue by Haelikor** [nicoboss/nsz#128]
Traceback has stated line 168 and 62 of __init__.py referencing args.long has the error of "AttributeError: 'arguments' object has no attribute 'long'"

All dependencies are met and no other errors come up. 

This only comes up once an attempt to compress a game begins. I appreciate any assistance rendered and will provide more information if necessary.

**Comment by nicoboss** [comment]
Thanks a lot for reporting this. In case you used the graphical user interface this issue is fixed now in the latest [NSZ 4.2.1](https://github.com/nicoboss/nsz/releases/tag/4.2.1) release. Please verify if this release fixes your issue. If your issue is not related to the graphical user interface please provide the command line arguments you used.

**Comment by Haelikor** [comment]
That fixed it. I appreciate the fast reply!
