### ISSUE TITLE
Empty update and normal partitions from XCI

### ISSUE THREAD

**Issue by sekelje** [nicoboss/nsz#156]
Hi,

I have a few xci dumps with system update removed, but with update and normal empty partitions still present. It works as expected in emulators. But, after compressing to xcz empty partitions are removed and after decompressing emulators won't detect nor manually start  xci's. I have tried other tools for compressing and decompressing which do not remove empty partitions. Is there a way to keep those empty partitions with your program?

Thanks

**Comment by nicoboss** [comment]
> Hi,
> 
> I have a few xci dumps with system update removed, but with update and normal empty partitions still present. It works as expected in emulators. But, after compressing to xcz empty partitions are removed and after decompressing emulators won't detect nor manually start xci's. I have tried other tools for compressing and decompressing which do not remove empty partitions. Is there a way to keep those empty partitions with your program?
> 
> Thanks

Thanks a lot for reporting this issue. This is now fixed in the latest [NSZ 4.6.0](https://github.com/nicoboss/nsz/releases) release. With the latest release the content of all but the secure partition is removed but the empty partition itself are kept by default. This results in Yuzu emulator compatibility. Specify --keep to keep all partitions including their content. This was implemented as part of a major XCI/XCZ rewrite so many other issues related to XCI/XCZ where fixed in the latest release as well.

**Comment by sekelje** [comment]
Thank you for making your program better.
I have done some testing, update and normal partitions are kept after compressing, but after decompressing xci's are not bit identical. I don't mind as long as it works, but is that to be expected? Probably worth mentioning, xci's have been "cleaned" with NSC Builder.

**Comment by nicoboss** [comment]
> Thank you for making your program better. I have done some testing, update and normal partitions are kept after compressing, but after decompressing xci's are not bit identical. I don't mind as long as it works, but is that to be expected? Probably worth mentioning, xci's have been "cleaned" with NSC Builder.

Thanks a lot for your testing and confirming that everything is working as intended. Currently only NSP/NSZ are bit-identically recreated so this is expected behavior. There is not much to worry about it as all NCA files inside the HFS0 file-system are already bit-identically recreated. With the major XCI/XCZ rewrite in NSP 4.6 things are getting quite close to bit-identical recreation but still a lot of work is required to get the HFS0 recreation bit-identical. For further discussion about this topic take a look at #147: "Full XCI (Key Area + XCI) and reversible XCZ". The No-Intro standard now supports XCI so bit-identical recreation makes a lot of sense and is planned for the next major version.
