### ISSUE TITLE
can you include [.switch] folder inside the app root?

### ISSUE THREAD

**Issue by bryanray** [nicoboss/nsz#175]
can you include [.switch] folder inside the app root?
so I will keep it as portable.
thanks

**Comment by bryanray** [comment]
so no .switch folder in C:/user/ anymore?

if that true, it is fantastic, it should be default like this....

**Comment by bryanray** [comment]
it should be this, FULL portable(actually working like a mac app), not half portable(have to place a folder to c/users/xxx)

**Comment by bryanray** [comment]
the "prod.keys" renaming to "keys.txt" could just change to (prodkeys.txt)

like actually changing the suffix, not change "format" 

you know, just make it more streamline and accustom to stupid people like me.

no bariner.

thanks!!!

**Comment by Masamune3210** [comment]
There is no "default mode", the file is supplied by the user. Put it in whichever you want to do. Using .switch is common for switch tools, having it be supported is quite useful as its less duplication of data.

**Comment by nicoboss** [comment]
Since the first release nsz supported booth prod.keys in `%USERPROFILE%/.switch/` and `keys.txt`  in the working directory. This always was and still is clearly mentioned in the README.md: "The keys file must be located as `prod.keys` file in `%USERPROFILE%/.switch/`(Windows)/`$HOME/.switch/`(UNIX) or `keys.txt` in the working directory.". nsz always was designed with portability in mind which is why all Windows releases are packed in a portable way. NSZ cannot and never will be able to come with any keys in order to not violate copyright law. Doing everything legal is essential for this project’s survival.
