### ISSUE TITLE
Please add new master_keys v11 and v12 support.

### ISSUE THREAD

**Issue by JrRadiant** [nicoboss/nsz#187]
Hello dear Nico Bosshard!

Please add new master_keys v11 and v12 support. If you need them, I've got it for you. Or just google it. :)
Thanks in advance!

**Comment by nicoboss** [comment]
The crc32 checksums of master_keys v11 and v12 were added in https://github.com/nicoboss/nsz/pull/177 and https://github.com/nicoboss/nsz/pull/185. There was no release since 18th December 2023 so you need to run latest master to have them. Those are just checksums to make sure the keys you extracted from your Nintendo switch console correct. Please dump your keys and not pirate them. Their crc32 checksums not being present just means that they can't be verified but does not impact the functionality of this application in any way. All current and future keys are supported in the current release. I plan on doing another release during this year’s Christmas holiday.
