### ISSUE TITLE
Failed to determinate TitleID/Version!

### ISSUE THREAD

**Issue by Mat37** [nicoboss/nsz#29]
I got this error while trying to decompress the update of Super Mario Party, but it happened with others updates. I compressed it with solid compression and level 22 and it went fine. I'm using the latest commit and here's the log i get
[1.txt](https://github.com/nicoboss/nsz/files/3828663/1.txt)

**Comment by nicoboss** [comment]
Strange works fine for me: [1.txt](https://github.com/nicoboss/nsz/files/3828781/1.txt)

Could you please post the result of "python .\nsz.py -V '.\Super Mario Party 1.0.1 [010036B0034E4800] v65536.nsz'"?

Please execute "python .\nsz.py -x '.\Super Mario Party 1.0.1 [010036B0034E4800] v65536.nsz'" and sha256 hash 59ada0e77ac0312142520f34960531ef.cnmt.nca inside the newly created "Super Mario Party 1.0.1 [010036B0034E4800] v65536" folder.  Use for example http://onlinemd5.com/ and select SHA-256 to get it's sha256 hash. I assume 59ada0e77ac0312142520f34960531ef.cnmt.nca is either missing or corrupted. The proper sha256 hash of 59ada0e77ac0312142520f34960531ef.cnmt.nca is 59ADA0E77AC0312142520F34960531EF3B5DF188FB0812A5FBEC79644A45A8BB.

Just in case you wonder why it even pharses the Cnmt. The filename contains the tile ID and Version but it expects the version to be like [v65536] as otherwise v0 could have false positives. It's planed to disable Cnmt pharsing by default in the next few days but this issue should be fixed anyways because enabeling it will still be an option.

**Comment by Mat37** [comment]
Here's the log for verification : 
[verify.txt](https://github.com/nicoboss/nsz/files/3829090/verify.txt) 
The Checksum for the CNMT is 59ADA0E77AC0312142520F34960531EF3B5DF188FB0812A5FBEC79644A45A8BB
so it's indeed correct.
What is weird to me is the fact that it also happened with the update of Luigi's Mansion 3 which i downloaded from a source that verify the file before uploading (i downloaded the NSZ directly).
I was about to post a log of this but it works with the latest commit.

**Comment by nicoboss** [comment]
As you can see inside verify.txt every verification check fails too. This is probably because it can't extract any file hashes from the CNMT. What's strange is how there isn't any error what makes it quite hard to debug especially because there is no way for me to recreate your issue. That your CNMT has the same exact hash makes thing even stranger. I really expected this to be a scene game where idiots removed tickets and carts but this isn't the case as I can see them in your verification log.

This issue is so special it might even have something to do with your environment so before we go any further I built latest commit as python independently portable exe for you using "nuitka nsz.py --standalone --plugin-enable=multiprocessing" - let's see if this issue occurs there too: http://www.nicobosshard.ch/nsz/nsz_nuitka_ab76c8e_portable.zip

**Comment by Mat37** [comment]
The same error happens while decompressing : 
[decompress.txt](https://github.com/nicoboss/nsz/files/3830656/decompress.txt)
The NSZ are still marked as corrupted when verifying : 
[verify.txt](https://github.com/nicoboss/nsz/files/3830660/verify.txt)
I redownloaded the update NSP and tried to compress it but apparently i can't decrypt the NCA (despite my keys.txt having up to master_key_06) :
[compress.txt](https://github.com/nicoboss/nsz/files/3830668/compress.txt)

**Comment by Mat37** [comment]
So i updated my switch to 9.0.1 and dumped the new keys, compression worked. I was able to decompress the file afterwards as well.
