### ISSUE TITLE
Can nsz.py script be made into pip package?

### ISSUE THREAD

**Issue by Dreamisdead** [nicoboss/nsz#30]
Like 'nsz' cli command.
Would be 10 times easier to install and use.
Or this script is not intended to be used like that?

**Comment by nicoboss** [comment]
Great idea! That would really make it much easier to install.
I have to restructure the project for this but planned to do this anyways.
Here the branch I'm working on to make this project pip compatible: https://github.com/nicoboss/nsz/tree/pip

**Comment by nicoboss** [comment]
Done: https://pypi.org/project/nsz/
Put dumped prod.keys to %userprofile%/.switch, install python, execute "pip install nsz" and use "nsz" like every other cmd command.
I even made a new release because of it: https://github.com/nicoboss/nsz/releases/tag/2.1
Thanks a lot for your great recommendation.
