### ISSUE TITLE
If exception happens during the compressing process, the created nsz file stub is not deleted

### ISSUE THREAD

**Issue by skygunner** [nicoboss/nsz#40]
2.1.1

For example, if there's exception during processing:

Traceback (most recent call last):
  File "D:\nsz\BlockCompressor.py", line 122, in blockCompress
Exception: NCA can't be decrypted. Outdated keys.txt?
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\nsz\__init__.py", line 137, in main
  File "D:\nsz\__init__.py", line 36, in compress
  File "D:\nsz\BlockCompressor.py", line 228, in blockCompress
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process:

There will be a 52KB .nsz file created but not removed. 
I think if there's exception during the process, the result should be removed to preventing confusing. 

Also when the cause of the exception solved, (updating the keys), even without -w overwrite directive, the programm will still overwrite the bad 52KB nsz file. 
Maybe here we should not overwrite it .

**Comment by nicoboss** [comment]
It tries to delete the file but can't because it's still open somewhere that's also why it shows: PermissionError: [WinError 32] The process cannot access the file because it is being used by another process
I will look into it but it's not an important enough to delay the NSZ 3.0 release in my opinion.

The overwrite issue was a major bug and fixed in https://github.com/nicoboss/nsz/commit/7f7a8514356a76c9ed01b576b91c02e23cef4009 which will be in todays NSZ 3.0 release.

The bad error messages occurring when providing outdated keys is already mentioned in https://github.com/nicoboss/nsz/issues/29 and will be made more clearer in the future.

**Comment by skygunner** [comment]
Have tried with newest keys and works fine. 

On overwrite: I'd think it should not overwrite if a file has the exact same name, or a nsz file has the same titleID and version.
