### ISSUE TITLE
Failed to extract TitleID/Version from filename ... Use -p to extract from Cnmt.

### ISSUE THREAD

**Issue by popy2k14** [nicoboss/nsz#47]
Hey guys.

Tried to compress several XCI backups and the following error pops up on almost every game i have tried. here is the error:

> Failed to extract TitleID/Version from filename .. Use -p to extract from Cnmt.

And here the output when i try to decompress the xcz WHICH FAILED:

> Failed to extract TitleID/Version from filename ... Use -p to extract > > from Cnmt.
> Error when decompressing file: ...
>  Traceback (most recent call last):
>    File "nsz\__init__.py", line 219, in main
>    File "nsz\__init__.py", line 62, in decompress
>  TypeError: decompress() missing 1 required positional argument: 'pleaseNoPrint'
> Failed to extract TitleID/Version from filename ... Use -p to extract > from Cnmt.
> Error when decompressing file: ...
>  Traceback (most recent call last):
>    File "nsz\__init__.py", line 219, in main
>    File "nsz\__init__.py", line 62, in decompress
>  TypeError: decompress() missing 1 required positional argument: 'pleaseNoPrint'

Any hints what i am doing wrong? :-)

thx

**Comment by nicoboss** [comment]
> Failed to extract TitleID/Version from filename .. Use -p to extract from Cnmt.

This just means it can't extract the titleid/version from the filename and without specifying -p to allow phrasing this information from the Cnmt nca some feature like overwriting/skipping only partially work using basic file name comparison and others like for example deleting outdated updates won't work for this file at all. It's just a warning that should make you consider using the -p option if you need one of the above features. The reason why -p isn't enabled by default is because most don't care about the enhanced file existing functionalities and phrasing the Cnmt is kind of slow when dealing with a lot of badly named files but other than speed enabling it has absolutely no disadvantages. Expected filenames to extract titleid/version is *ID*[vVersion]* where * is a placeholder for any amount of characters.

XCI decompression was broken in prior to nsz v3.1.1 so update to the latest release and you should be fine.
