### ISSUE TITLE
kivy dep not in distro repo, any way around it?

### ISSUE THREAD

**Issue by gut5** [nicoboss/nsz#48]
```ERROR: Could not find a version that satisfies the requirement kivy_deps.sdl2==0.1.22 (from -r requirements.txt (line 4)) (from versions: none)
ERROR: No matching distribution found for kivy_deps.sdl2==0.1.22 (from -r requirements.txt (line 4))
```
I'm getting this in my distro (Clear Linux, which admittedly doesn't have the best repo), is there any way to get around this dep?
Trying on 3.1.0 btw.

**Comment by nicoboss** [comment]
Don't use requirements.txt for Linux. It's made for Windows and contains dependencies only available for Windows. For Linux use requirements_linux.sh (and maybe slightly edit it to fit your distribution) is recommended. If you don't mind using PyGame instead of SDL2 as GUI backend try "pip3 install nsz" and it maybe just work depending on your distribution but using requirements_linux.sh is recommended for Linux.
By the way please reclone/redownload the 3.1.0 release as you probably got the wrong commit because you downloaded very early after the release and I had the 3.1.0 tag pointing to the wrong commit during the first few minutes.

**Comment by nicoboss** [comment]
I assume in the meantime you were able to install nsz on your Linux distribution so I'm closing this now. If your problem still persists just reopen this issue. Feel free to always ask me if you need any help installing nsz.
