### ISSUE TITLE
OSError trying to find a key that its not present

### ISSUE THREAD

**Issue by AzureusPT** [nicoboss/nsz#68]
Trying to compress a XCI ends giving me the following error:

    OSError: master_key_10 missing from keys.txt

I have keys from 9.1/9.2, which go as high as key_0a (not key_10). The game works under that firmware, so the script should be able to read it without issues. Any idea why its trying to reach for a key that its not present?

I'm using the most up-to-date code. I've tried to reverting to the commit of release 3.1.1 and the error its slightly different, but in the end it says the same, that I it can found a master_key_10.

Command used to run the script was:

    python nsz.py -CV -o /<path>/ $HOME/Downloads/<file>.xci

This is the full traceback (using [866337a](https://github.com/nicoboss/nsz/commit/866337a173e4508ec8db04dc52899314622766d4)):
```
    Error when compressing file: /home/<user>/Downloads/<file>.xci
    Traceback (most recent call last):
      File "/home/<user>/Repositories/NSZ/nsz/__init__.py", line 154, in main
        compress(filePath, outfolder, args, work, amountOfTastkQueued)
      File "/home/<user>/Repositories/NSZ/nsz/__init__.py", line 50, in compress
        outFile = blockCompress(filePath, compressionLevel, args.bs, outputDir, threadsToUseForBlockCompression)
      File "/home/<user>/Repositories/NSZ/nsz/BlockCompressor.py", line 33, in blockCompress
        return blockCompressXci(filePath, compressionLevel, blockSizeExponent, outputDir, threads)
      File "/home/<user>/Repositories/NSZ/nsz/BlockCompressor.py", line 218, in blockCompressXci
        container.open(str(filePath), 'rb')
      File "/home/<user>/Repositories/NSZ/nsz/Fs/Xci.py", line 294, in open
        self.partition(0xf000, None, self.hfs0, cryptoKey = None)
      File "/home/<user>/Repositories/NSZ/nsz/Fs/File.py", line 67, in partition
        n.open(None, None, cryptoType, cryptoKey, cryptoCounter)
      File "/home/<user>/Repositories/NSZ/nsz/Fs/Hfs0.py", line 140, in open
        self.files.append(self.partition(offset + headerSize, f.size, f))
      File "/home/<user>/Repositories/NSZ/nsz/Fs/File.py", line 67, in partition
        n.open(None, None, cryptoType, cryptoKey, cryptoCounter)
      File "/home/<user>/Repositories/NSZ/nsz/Fs/Hfs0.py", line 140, in open
        self.files.append(self.partition(offset + headerSize, f.size, f))
      File "/home/<user>/Repositories/NSZ/nsz/Fs/File.py", line 67, in partition
        n.open(None, None, cryptoType, cryptoKey, cryptoCounter)
      File "/home/<user>/Repositories/NSZ/nsz/Fs/Nca.py", line 215, in open
        self.partition(0x0, 0xC00, self.header, Fs.Type.Crypto.XTS, uhx(Keys.get('header_key')))
      File "/home/<user>/Repositories/NSZ/nsz/Fs/File.py", line 67, in partition
        n.open(None, None, cryptoType, cryptoKey, cryptoCounter)
      File "/home/<user>/Repositories/NSZ/nsz/Fs/Nca.py", line 118, in open
        self.keyBlock = Keys.unwrapAesWrappedTitlekey(self.encKeyBlock, self.masterKey)
      File "/home/<user>/Repositories/NSZ/nsz/nut/Keys.py", line 92, in unwrapAesWrappedTitlekey
        kek = generateKek(getKey('key_area_key_application_source'), getMasterKey(keyGeneration), aes_kek_generation_source, aes_key_generation_source)
      File "/home/<user>/Repositories/NSZ/nsz/nut/Keys.py", line 110, in getMasterKey
        return getKey('master_key_{0:02}'.format(masterKeyIndex))
      File "/home/<user>/Repositories/NSZ/nsz/nut/Keys.py", line 99, in getKey
        raise IOError('{0} missing from {1}'.format(key, loadedKeysFile))
    OSError: master_key_10 missing from keys.txt
```

**Comment by deadair3210** [comment]
it shouldn't be a critical error, most tools check for the presence of either masterkey_10 or 0a to catch either. they are the same key, just different way of counting. if the error bugs you, make a dup entry for it, one for 0a and one for 10

**Comment by AzureusPT** [comment]
Sorry if I wasn't clear enough, but the script doesn't do anything more aside failing. If it was a warning I suppose it should be able to continue, but I just get the prompt back without any file being created.

Here's the full output of the run: [https://pastebin.com/unQ3XBYH](https://pastebin.com/unQ3XBYH)

As for cloning key_0a onto key_10, the script seems to work well compressing (aside the CRC warnings), but the resulting file fails once installed. I'm using Awoo and both original XCI and compressed XCZ install without issues, but once you try to run it, the first one runs without problems and the second gives an error:

```
Error Code: 2002-4000
The software was closed because an error ocurred.
```

Here's the full output of the run, when creating a duplicate key_10 (from key_0a): [https://pastebin.com/dFPF1D7b](https://pastebin.com/dFPF1D7b)

**Comment by deadair3210** [comment]
Either I'm wrong about the whole 10=0a thing (which is possible), or your key is wrong

**Comment by AzureusPT** [comment]
I hope keys aren't wrong, since they where dumped from a working system (not downloaded from the internet). Might it be that its using master_key_10 but since that doesn't exist on the working system, this last one isn't able to properly launch it?

**Comment by nicoboss** [comment]
I can confirm that crc32(master_key_0a) = 2012895168 and so your key is correct. Back when I implemented support for keys after master_key_09 it was unclear how we continue to count and I wrongly assumed it would be master_key_10. We now count in hexadecimal and so it's master_key_0a. I will fix that in the next release.
I never tested any game that uses master_key_0a so no idea what went wrong. Generally, XCZ compression is kind of broken in the last release as it only compresses NCA files with the first section starting at 0x4000 and so doesn't compress quite a large amount of NCA files as often inside XCI containers they start at 0x4200. This bug is fixed in master but barely tested.

What most likely caused your game to be corrupted after installing is just https://github.com/nicoboss/nsz/issues/42 as by default XCI compresses to a block compressed XCZ which is currently not supported by Awoo Installer. Block compression is only so in the future it’s possible to play compressed games directly on your Nintendo Switch and emulator without decompressing it first. Before SciresM will reimplement fs next year I don’t think block compressed NSZ/XCZ games on real hardware will happen So just use solid compression --solid for XCI games if you want them to be Awoo compatible.

Generally, I recommend waiting for next release before you compress all your XCI games or use master instead. If you use master please give feedback if it works for all your games. You can always use the –verify option to see if compression was successful.

**Comment by AzureusPT** [comment]
Argh... I forgot about the `--solid` option, sorry.

Running the script from `master` successfully compresses the XCI and its installable/playable. The only workaround needed its to duplicate key_0a with key_10, else it doesn't do much.

**Comment by maki-chan** [comment]
A fix would be easy. Only `nsz/nut/Keys.py` has to be fixed in line `110` and `113`. You simply have to use `{0:02x}` instead of the `{0:02}` format specifier in those two lines.
