### ISSUE TITLE
Why is hfs0 header size modified?

### ISSUE THREAD

**Issue by Mz49** [nicoboss/nsz#77]
Hello. I was looking through the code and trying to get an understanding of how it all works. I'm having trouble understanding the purpose of modifying the hfs0 header size.

https://github.com/nicoboss/nsz/blob/30577fe75f56b296bd6cec8a30e57c5cfb567053/nsz/Fs/Xci.py#L82-L84

This function is called every time an XciStream is close, and hence every XCZ made with nsz will result in the header size modified. What is the reason behind this? Am I missing something?

**Comment by nicoboss** [comment]
Thanks a lot for pointing that out. I have no idea why we changed the HFS0 header size. This code originates from NUT which was developed quite early when parts of the HFS0 file format were still unknown so probably it was thought this indicates the whole file size instead of the HFS0 header size. I removed it in the latest NSZ v4.0 release as there seems to be absolutely no reason for this to be required and as a lossless compression format XCZ should never modify values inside the file irreversible. The only reason this was never noticed was because unlike the NCA files there were no easily accessible checksum to verify the headers integrity and changing the header size had no impact on real hardware.
