### ISSUE TITLE
Can't repack into NSP? (log file enclosed)

### ISSUE THREAD

**Issue by CoffeeIsLife87** [nicoboss/nsz#78]
[errors.txt](https://github.com/nicoboss/nsz/files/4920873/errors.txt)

**Comment by nicoboss** [comment]
This issue should be fixed in the latest [NSZ v4.1.0](https://github.com/nicoboss/nsz/releases/tag/4.2.0) release. Please let me know if you still experience this issue on the latest release. It was reported and fixed as part of https://github.com/nicoboss/nsz/issues/118

I looked at the provided logfile again and saw that you probably meant to do something completely different and only found this issue on accident. Please keep in mind that "-c" means --create (repacking NCA/NCZ files) while "-C" means Compress (used to compress NSP/XCI files). Using -c in combination with an NSZ file makes no sense. You probably wanted to use "-D" to decompress the NSZ to an NSP.
