### ISSUE TITLE
nsz doesnt respect -o flag when decompressing

### ISSUE THREAD

**Issue by fennectech** [nicoboss/nsz#87]
[fennectech@jasper ~/Backup/NSP]$  nsz -D ../NSZ/*.nsz -o /home/fennectech/Backup/NSP -m 4
is the command i used

**Comment by nitro322** [comment]
I was just coming to file a request for this issue.  Would not a bug since the help file explicitly states "output NSZ files", but I think users would generally expect the output flag to work for both compressed and decompressed files (at least, I do).

Would appreciate if you'd update the -o option to support decompression as well, or add another option for changing the location of decompressed files if you think that makes sense.  As it stands now, it seems to be impossible to decompress the file to any location except where the NSZ file is located.

**Comment by nitro322** [comment]
Thanks!  I had actually looked at the code and was going to try to submit a pull request for this, but I have very limited experience with python and had trouble figuring out why this wasn't working.  Very much looking forward to a fix.

**Comment by fennectech** [comment]
Its almost always something stupid.    The thing you dont notice.

**Comment by nicoboss** [comment]
This issue was caused by trying to joined two full paths instead of a full path with the filename (a relative path). This resulted in the path to the extension changed source file to overwrite the destination path instead of joining the destination folder with the extension changed source file. This is fixed now and will be in the next release which should come soon.

**Comment by fennectech** [comment]
Yep   Definitly something stupid :)

**Comment by nitro322** [comment]
Yay!  Just tested from source and seems to be working as expected now.  Thanks a bunch!
