### ISSUE TITLE
Restore/Keep delta fragments?

### ISSUE THREAD

**Issue by mid-kid** [nicoboss/nsz#89]
I'm going through my library and compressing things in the hope I can squeeze some more space out of my drives, and I couldn't help but notice that this program throws away something called "delta fragments". A post in the GBATemp thread suggests they are completely useless, but I couldn't find any info about the format of these fragments or the NDV0 format at all (even on switchbrew.com) so I'm not sure what _can_ be done with them. If they can be used for example to reconstruct any previous update, I'd love to keep them, for archival purposes, as opposed to keeping every update separately.
I read that nsZip was able to completely remove and reconstruct these based on their header, and since it doesn't interfere with homebrew installers, why doesn't this tool have a similar function?

**Comment by blawar** [comment]
Those fragments don’t allow you to recreate old updates without the diff data itself as well, which is a lot more than just the header.

nothing can be done with them.  If you want to archive old updates, archive each update individually.

**Comment by nicoboss** [comment]
Delta fragments are used if you download the next update of a specific game. Instead of downloading the RomFs Patching information (BKTR partition) which tells the game what changed in comparison to the base game it downloads an applies a delta fragment to the BKTR partition of the previous update. That way a lot of CDN bandwidth gets saved as only the delta between the two subsequent updates need to be downloaded. After applying the delta fragment to the previous update, you get exactly the same as if you had downloaded the new update. For this to work you obviously also need all the other smaller files of the new update and not just the previous updates BKTR partition and delta fragments. If anything, you would want to fully store the first update and the delta fragments plus everything not covered by the delta fragments of every following update. Make sure no update is missing in-between as you would need all of them in order to hop forward in time from update to update. But honestly this is like the most stupid thing so just don't do that. Better use one of the many 3rd party tools to keep track of the BKTR partition change history in their own format and somehow implement this in this tool before compression. I'm honestly quite interested in this topic as I have the same problem and might see if there is an easy solution after my exams and so probably in February. If you are just interested in the NDV0 format I highly recommend checking out the nsZip source code as there I completely trimmed them to a few kilobytes and recreate them. This can be done as nsZip also stores the BKTR partition of every update and so trimming fragments to their header can be undone by reconstructing them using the BKTR partition by doing the exact opposite they are meant to do. This is absolutely useless and I mostly made it for fun and interest in the NDV0 format which is also the reason why it's not included in NSZ. Take a look at https://github.com/nicoboss/nsZip/blob/master/LibHac/Fs/DeltaFragment.cs and https://github.com/nicoboss/nsZip/blob/master/LibHacExtensions/RecreateDelta.cs if you are interested how in the NDV0 format. You can use https://github.com/Thealexbarney/LibHac to play around and apply delta fragments.

**Comment by nicoboss** [comment]
I did some investigations about this today. As expected keeping delta fragments is absolutely useless as it is nothing that would make any sense for archiving old updates. I also heard that there is interest in a file format that lets you put all game related content together in a single file for archival purposes. While doing so we could define a pivot based on the latest updates NCAs containing patching information. For every update we pack into that container we only store the reverse diff to that pivot. That way you have this container where you can put all game related things into and save a lot of storage when dealing with multiple updates of the same game. By only diffing against a specific version you also don't add much complexity as never more than one diff needs to be applied. In order to add or remove something from that container all data needs to be rewritten and deltas might need to be recalculated. I’m quite interested in creating such a file format but keep in mind that it’s extremely unlikely to gain any adoption outside archival.

**Comment by mid-kid** [comment]
I see. Thanks for the extensive explanation and looking into the issue. If such a format came to exist while allowing signature verification of every update I'm sure it'd become useful in the future with romsets, even if not noteworthy for the general player.
For now, just knowing for sure that the deltas are useless makes me feel more comfortable removing them. I wonder why they're distributed in nsps at all.

**Comment by blawar** [comment]
Most of the scene moved away from deltas years ago.  The "official" scene still dumps them for the appearance that their dumps are more original or pure.  They even go as far as to recreate xml metadata that actual game artists submit to Nintendo along with the patch, that Nintendo does not even serve to end users (those files are used internally by Nintendo only).  The only reason they know these files even exist anywhere is because of the leaked SDK.

Happy Festivus.
