### ISSUE TITLE
the program closes

### ISSUE THREAD

**Issue by Znagling** [nicoboss/nsz#90]
when I try to select the nsz file, the program immediately closes. this is only in version 4.0.0 and 4.0.1, I tried to select a file in version 3.1.1 and the program does not close. I will clarify that the program closes before I press the decompression button, I only select the file and press load and everything closes

**Comment by nicoboss** [comment]
This issue should already be fixed in latest master but is still broken in latest release. There will be another release in a few weeks. Until then I recommend to use command line arguments or latest master if you really want to use the GUI. The commit that fixed this is https://github.com/nicoboss/nsz/commit/0c1b2dd795292bac15956c9b533d19cb2fcd4152. I'm really sorry that I haven't made a release for such a long time. Creating releases requires quite some time which I barely have beside university but my semester ends late January so I should have a lot of time soon.

**Comment by nicoboss** [comment]
This issue should be fixed in the latest [NSZ v4.1.0](https://github.com/nicoboss/nsz/releases/tag/4.2.0) release. Please let me know if you still experience this issue on the latest release.
