### ISSUE TITLE
Original Rom Size

### ISSUE THREAD

**Issue by proconsule** [nicoboss/nsz#96]
It would be great if there is somewhere in the file the original decompressed file size, this will help titles installer or titles managers to know the decompressed weight of rom

**Comment by nicoboss** [comment]
That's exactly why the first 0x4000 bytes of an NCZ file are exactly the same as the original NCA file. In there you can find the original NCA header with all the information you need for any title installer/titles manager. Even better because this part is totally unmodified you don't even need to rewrite the title installer/titles manager to be compatible with NCZ if you are only interested in meta information. This includes information like ContentSize and an Array of FsEntry which contain StartOffset and EndOffset of the uncompressed NCA partitions. Please take a look at https://switchbrew.org/wiki/NCA for more information.

**Comment by proconsule** [comment]
Sure i know it, but this is done by decrypting NCA header and since is impossible on 32bit machine with php i am wondering a method to get the uncompressed size with another method.
Thanks for the answer.

**Comment by nicoboss** [comment]
That's exactly why there is the additional NCZSECTN header added at 0x4000 as stated in the README.md:
_"All of the information in the header can be derived from the original NCA + Ticket, however it is provided pre-parsed to make decompression as easy as possible for third parties."_

The only reason NCZSECTN exists is so developers of tools that support NSZ don't need to decrypt and phrase the original NCA header just to obtain the meta information.

It also gives you following example how to phrase it:
```python
class Section:
	def __init__(self, f):
		self.magic = f.read(8) # b'NCZSECTN'
		self.offset = f.readInt64()
		self.size = f.readInt64()
		self.cryptoType = f.readInt64()
		f.readInt64() # padding
		self.cryptoKey = f.read(16)
		self.cryptoCounter = f.read(16)

class Block:
	def __init__(self, f):
		self.magic = f.read(8) # b'NCZBLOCK'
		self.version = f.readInt8()
		self.type = f.readInt8()
		self.unused = f.readInt8()
		self.blockSizeExponent = f.readInt8()
		self.numberOfBlocks = f.readInt32()
		self.decompressedSize = f.readInt64()
		self.compressedBlockSizeList = []
		for i in range(self.numberOfBlocks):
			self.compressedBlockSizeList.append(f.readInt32())

nspf.seek(0x4000)
sectionCount = nspf.readInt64()
for i in range(sectionCount):
	sections.append(Section(nspf))

if blockCompression:
	BlockHeader = Block(nspf)
```
Isn’t the size of the NCZSECTN exactly what you need?

Alternatively you could maybe also use ZSTD_getFrameContentSize() or extract the ZStandard "Frame Content Size" filed manually. See https://tools.ietf.org/id/draft-kucherawy-dispatch-zstd-01.html It definitely would be possible to phrase the original NCA header using PHP assuming it has access to the required keys as it's just AES but NCZSECTN should be exactly what you are looking for.

Thanks a lot for supporting NSZ inside NSP Indexer. I highly appreciate it. Please Let me know if you have any further questions.

**Comment by nicoboss** [comment]
Yes, I actually use NCZSECTN inside my own tool to calculate the size of the decompressed NCA before actually decompressing it. I do so like this:
```python
sectionCount = readInt64(nspf)
	sections = [Section(nspf) for _ in range(sectionCount)]
	nca_size = 0x4000
	for i in range(sectionCount):
		nca_size += sections[i].size
````
If you want the size of the entire NSZ/XCZ just sum up the size of all the files inside and if compressed use the NCZSECTN to get the decompressed size.

**Comment by proconsule** [comment]
Your implementation is very smart, i have the only limit of 32bit fseek (on 32bit machines) but since other NCA are so small i can seek the file to this offset. i'll try it and let you know.
Thanks for all and for code examples. very clear!

**Comment by nicoboss** [comment]
Thanks. A lot of thought went into the NSZ file format and I tried very hard to make my file format as easy to use for everybody. NSZ being that easy to use is exactly what lead to its wide adoption and success. My previous nsZip project with the same goal failed due to the NSPZ file format being way too overcomplicated. I learned my lesions and took all the experience I gained from nsZip to make NSZ the best file format I could.

For your issue with PHP x86 fseek I did some research. Under https://www.php.net/manual/en/function.fseek.php in the comments there is a great example how to seek files larger than 2 GB on PHP x86 by using recursion and floating-point numbers:
```php
// seek / set file pointer to 50 GB
my_fseek($fp, floatval(50000000000),1);

function my_fseek($fp,$pos,$first=0) {

// set to 0 pos initially, one-time
if($first) fseek($fp,0,SEEK_SET);

// get pos float value
$pos=floatval($pos);

// within limits, use normal fseek
if($pos<=PHP_INT_MAX)
  fseek($fp,$pos,SEEK_CUR);
// out of limits, use recursive fseek
else {
  fseek($fp,PHP_INT_MAX,SEEK_CUR);
  $pos -= PHP_INT_MAX;
  my_fseek($fp,$pos);
}
```
I haven't tested this and I'm no PHP expert but the author claims that this works with file sizes up to 100 petabytes. However, I wonder at what point floating point precision will cause seek precision issues.

**Comment by proconsule** [comment]
This can be a good trick, i'll try it.
The 32bit support is just to make it work on all machines, but 64bit is raccomended (we are in 2021) .
Now that i have all this info i can make a better nsz support (giving compressed and uncompressed size in the page).
Thanks far all your info, i really appreciate it!

**Comment by nicoboss** [comment]
I did some testing with PHP x86 and turned out that fseek past 2 GB with above method is broken - at least on Windows using XAMPP.

However, I found the following method which I successfully tested and does works perfectly fine on PHP x86. If floating point precision isn't enough use string manipulation or a library that implements 64-bit integers on php x86 or use GMP or BC Math extensions for big numbers if such a requirement is feasible.
```php
$start=floatval(12000000000); //12 GB
$len=floatval(1024); //1 KiB
$opts = array('http'=>array('method'=>'GET','header'=>"Range: bytes=$start-".($start+$len-1)));
$context = stream_context_create($opts);
echo $result = file_get_contents('http://127.0.0.1:8080/BigFile.sql', false, $context);
```
I agree that x86 in 2021 is kind of dead, so feel free to just make this x64 exclusive if you don't want to use ugly hacks to get it working with PHP x86.

I like helping developers to better support the NSZ file format. If you have any further questions feel free to ask.

**Comment by proconsule** [comment]
You ends up with a good trick but probably i dont support x86 with advanced features, because in a developing prospective i must use too many tricks for doing simple task, but thanks for the code it will be very usefull for other tasks.
You gave me a great support and i hope that your file type will be supported by all the title installer.
I for sure will support on a side project i am doing that is nsp-indexer-connect to directly install titles from NSP Indexer.

**Comment by proconsule** [comment]
With your help now i can report right infos:

Compressed Size 302.1 MiB
Original Size 1.4 GiB

Thank you a lot

**Comment by nicoboss** [comment]
That's so cool! I just tested your latest development version of your tool and it worked very well. I never used your tool before but I really like it.

During testing I noted a slight discrepancy between what size it gets and the real size of decompressed NSZ. The size inside games.json is slightly larger than it should. The difference is less than 10 MB and so quite small. If you care about precision, you likely have to use the sum from all the NCZSECTN sizes + 0x4000 or the largest FsEntry EndOffset from the NCA header instead of ContentSize. I looked at your code and everything seems correct so maybe ContentSize is just rounded up to a specific chunk size.

It would be cool if you could put booth sizes or the compression ratio on the webpage so users have a nice overview.

**Comment by blawar** [comment]
@proconsule you are already decrypting the NCA header, you can get the decompressed size from $this->contentSize:

https://github.com/proconsule/nspindexer/blob/master/lib/NCA.php#L53

**Comment by nicoboss** [comment]
He already ended up using contentSize:
https://github.com/proconsule/nspindexer/blob/875eed3c00615e5659d3ced5c92786759e05bc34/lib/NSP.php#L35
https://github.com/proconsule/nspindexer/blob/875eed3c00615e5659d3ced5c92786759e05bc34/lib/NCZ.php#L20

This works very well but for some reason there is a slight discrepancy between the decompressed size calculated by summing up the file size of uncompressed and the contentSize of compressed files. It's only a few megabytes but still quite strange that this results in a larger file. I would expect a size only a few KB lower (because he doesn't consider PFS0 metadta) size than real size. I’m not even sure if he cares about accuracy but getting a too large file size just seems so strange. Are you sure that contentSize inside the NCA header is an accurate representation of the NCA file size? I only know that NCZSECTN sizes + 0x4000 and largest FsEntry EndOffset are accurate representation of the NCA file size.

**Comment by proconsule** [comment]
> @proconsule you are already decrypting the NCA header, you can get the decompressed size from $this->contentSize:
> 
> https://github.com/proconsule/nspindexer/blob/master/lib/NCA.php#L53
> 
> edit: it seems you are saying AES-XTS decryption does not work on 32-bit? If so, can you point out which part of this file is not 32bit compatible?
> 
> https://github.com/proconsule/nspindexer/blob/master/lib/AES.php

mainly the unpack  and some $words[0] & 0xFF000000 since php 32bit is signed integer only.
probably using an extension like GMP ora the BigInteger that already use for RSA PSS can overcome the problems but i will do it later since many other things dont work well with 32bit PHP (like the unpack P for 64 bit offsets)

**Comment by proconsule** [comment]
@nicoboss i will try in this way, yes is a strange behaviour so i will check  in the way you suggested.

The NSZ.php for now is only a "subclass of NCA" but i made it to expand in future

**Comment by proconsule** [comment]
@nicoboss in rominfo now i put ratio and compression level for nsz files as you suggested.
yes is very cool!

**Comment by blawar** [comment]
> He already ended up using contentSize:
> https://github.com/proconsule/nspindexer/blob/875eed3c00615e5659d3ced5c92786759e05bc34/lib/NSP.php#L35
> https://github.com/proconsule/nspindexer/blob/875eed3c00615e5659d3ced5c92786759e05bc34/lib/NCZ.php#L20
> 
> This works very well but for some reason there is a slight discrepancy between the decompressed size and the size calculated by summing up the file size of uncompressed and the contentSize of compressed files. It's only a few megabytes but still quite strange that this calculation results in a larger file size. I would expect a size to be a few KB smaller because he doesn't consider PFS0 metadata. I’m not even sure if he cares about accuracy but getting a too large file size just seems so strange. Are you sure that contentSize inside the NCA header is an accurate representation of the NCA file size? I only know that NCZSECTN sizes + 0x4000 and largest FsEntry EndOffset are accurate representation of the NCA file size.

Can you provide the title id  and sha256 hash of the file you found the discrepancy in so I can take a look?

**Comment by blawar** [comment]
> @nicoboss i will try in this way, yes is a strange behaviour so i will check in the way you suggested.
> 
> The NSZ.php for now is only a "subclass of NCA" but i made it to expand in future

NSZ.php should be renamed to NCZ.php

**Comment by nicoboss** [comment]
> @nicoboss in rominfo now i put ratio and compression level for nsz files as you suggested.
> yes is very cool!

Awesome! Thanks a lot!

> Can you provide the title id and sha256 hash of the file you found the discrepancy in so I can take a look?

SPACE INVADERS INVINCIBLE COLLECTION[0100424012C94000]:
Filesize of NSZ: 817042208 bytes
Filesize size of NSP: 1191156672 bytes
Size calculated by the sum of uncompressed files and the contentSize of all compressed files: 1197473792 bytes
Difference: 6317120 bytes more when calculated using contentSize 
Same seams to apply for all games I checked.

> > @nicoboss i will try in this way, yes is a strange behavior so i will check in the way you suggested.
> > The NSZ.php for now is only a "subclass of NCA" but i made it to expand in future
> 
> NSZ.php should be renamed to NCZ.php

I think he actually meant NCZ.php: https://github.com/proconsule/nspindexer/blob/dev/lib/NCZ.php#L3 - there is no NSZ.php inside his project so he likely just confused the names.

**Comment by proconsule** [comment]
Yes i am confusing names, less beer while coding 😅

**Comment by blawar** [comment]
I found the file that matches that hash @nicoboss , and I verified that the contentSize is correct.  I also verified that your size of 1,191,156,672 is correct for the NSP.  the contentSize in the nca header is the full decompressed NCA size (including its header, the entire file).

The contentSize's in the NCA headers are as follows: 625664, 3584, 210944, 1190281216

the ticket and cert are 704 and 1792 respectively.

The sum of all of these sizes is 1191123904, which means  there is a difference of 32768 bytes, which can be accounted for by the PFS0 header and possibly file alignment.


(file size is the compressed size, size is the decompressed size and both numbers are correct).

```
        NCA Archive

        File Path: b98a5e6ef8c9016ee993c485af17d622.ncz
        File Size: 816166752
        verified header = True
        magic = b'NCA3'
        titleId = 0100424012C94000
        rightsId = 0100424012c94000000000000000000b
        isGameCard = 0x0
        contentType = Content.PROGRAM
        cryptoType = Crypto.NONE
        Size: 1190281216
        crypto master key: 2
        crypto master key2: 11
        key Index: 0

        FsSections:
                offset = 43C74000, endOffset = 46F24000
                offset = 1C000, endOffset = 43C74000
                offset = 4000, endOffset = 1C000


        FsHeaders:
        key Block Dec: ED27903DE7C595B2B5995CB9FC9FCA66
        key Block Dec: ED27903DE7C595B2B5995CB9FC9FCA66
        key Block Dec: ED27903DE7C595B2B5995CB9FC9FCA66
        key Block Dec: ED27903DE7C595B2B5995CB9FC9FCA66
        build Id: None
 ```

**Comment by nicoboss** [comment]
I now did a manual calculation too and can confirm that @blawar is correct. I also tasted the latest version or your tool where you use the size of NCZSECTN instead of contentSize and your algorithm comes to the same wrong result of 1197473792 bytes for above mentioned game. Something with your code must be wrong @proconsule. Please fix it so it matches the result of the manual calculation @blawar described in his last post. You then should also get 1191123904 bytes for above mentioned game.

**Comment by nicoboss** [comment]
Sorry, there is a huge misunderstanding. I did some debugging and realized that no matter what I change inside the getRealSize() function (https://github.com/proconsule/nspindexer/blob/5562ecbd8a2a05712fce91b2d0824412ec6268fd/lib/NSP.php#L30) nothing changes inside games.json. So likely your calculation is correct but you just don't use it for games.json. The wrong number we kept talking about actually seems to originate from the size property inside titles.json. Sorry for all the confusion and troubles I caused.

> @nicoboss in rominfo now i put ratio and compression level for nsz files as you suggested.
> yes is very cool!

How do I open rominfo? I don't see any such function on the webpage.

**Comment by proconsule** [comment]
You have to provide prod.keys and set the path to it in config.php

If you copy it in the same dirctory of index.php it will just be prod.keys as path

**Comment by nicoboss** [comment]
Thanks a lot! I got rominfo working. I had a typo in the prod.key config path.

I got latest commit on dev branch and modified bytesToHuman inside nspindexer.js to show me bytes and now am getting the desired 1191123904 bytes. This matches exactly what we manually calculated and verifies that everything with your code is correct. Sorry for all the troubles I caused. I wasn’t aware that with rominfo you don't mean games.json. The reason why games.json shows the wrong size is because it's based on titles.json which again is based on the original NSP file which contains a lot of useless files that all add to the size.

Your title manager is awesome and I definitely will make use of it! Thanks a lot for making it. I love how you can download files packed inside a PFS0 container. Doing this over your title manager is so much more convenient compared the --extract/--extractregex options of my tool.

![image](https://user-images.githubusercontent.com/623410/132560575-fb83a4e2-a77e-4214-b6ea-6505886bb10f.png)

**Comment by proconsule** [comment]
Now i am working on extract individual files inside nca (and ncz also but later because i have to port zStd in pure php)

Also with XCI you can download update partition as single tar file (to get the switch os) all on the fly no temp file used, and is pretty fast (considering is all in PHP)

**Comment by blawar** [comment]
@nicoboss if he is getting the size info from titledb, it will always be off as nintendo does some fuzzy logic there and the size is base + update, not just the base.  I gave up trying to understand nintendo's numbers there.

**Comment by proconsule** [comment]
In the frontend i have size and real_size, size is from titles db real_size is from a filesize php command on the file.

The frontend show real_size to user.
